import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ReactQueryClientProvider } from "@/components/react-query-provider";
import React from "react";
import { AppSidebar } from "@/components/root-layout/sidebar/app-sidebar";
import { Toaster } from "@/components/ui/sonner";
import { CheckDocProcessing } from "./documents/components/check-doc-processing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Advanced RAG",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <head>
        <script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
      </head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryClientProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <div className="flex">
              <CheckDocProcessing />
              <aside>
                <AppSidebar />
              </aside>
              <main className="flex-1">{children}</main>
            </div>
            <Toaster richColors />
          </ThemeProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
